server.port=${PORT:8000}

proxy.monolith-url=${MONOLITH_URL:http://localhost:8080}
proxy.movies-service-url=${MOVIES_SERVICE_URL:http://localhost:8081}
proxy.events-service-url=${EVENTS_SERVICE_URL:http://localhost:8082}
proxy.gradual-migration=${GRADUAL_MIGRATION:true}
proxy.movies-migration-percent=${MOVIES_MIGRATION_PERCENT:50}

# suppress Spring Boot banner noise
logging.level.root=INFO
